apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-reader
  labels:
    app: app
    type: reader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      type: reader
  template:
    metadata:
      labels:
        app: app
        type: reader
    spec:
      containers:
      - name: app-reader
        image: app:reader
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-reader-service
spec:
  selector:
    app.kubernetes.io/name: app-reader
  ports:
    - protocol: TCP
      targetPort: 80