apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-issuer
  labels:
    app: app
    type: issuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
      type: issuer
  template:
    metadata:
      labels:
        app: app
        type: issuer
    spec:
      containers:
      - name: app-issuer
        image: app:issuer
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-issuer-service
spec:
  selector:
    app.kubernetes.io/name: app-issuer
  ports:
    - protocol: TCP
      targetPort: 80